// 00-4-all-time/Useful-Tools-repos/WebTemplateStudio/templates/Web/Pages/Angular.List/frontend/src/app/app-shell/Param_SourceName_Kebab/list-item/list-item.component.ts
﻿import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { IParam_SourceName_PascalItem } from '../Param_SourceName_Kebab.model';

@Component({
  selector: 'app-list-item',
  templateUrl: './list-item.component.html',
  styleUrls: ['./list-item.component.css']
})
export class ListItemComponent implements OnInit {
  // tslint:disable-next-line:variable-name
  @Input() id: string;
  @Input() listItem: IParam_SourceName_PascalItem;
  @Output() deleteItem = new EventEmitter<string>();

  constructor() {}

  ngOnInit(): void {}

  deleteItemFn(): void {
    this.deleteItem.emit(this.id);
  }
}

﻿<div class="row">
  <div class="col-11">
    <p class="mt-3">{{ listItem.text }}</p>
  </div>
  <div class="col-1">
    <button
      type="button"
      class="close py-2"
      data-dismiss="alert"
      aria-label="delete"
      title="Delete"
      alt="delete"
      (click)="deleteItemFn()"
    >
      <div aria-hidden="true">&times;</div>
    </button>
  </div>
</div>

// 00-4-all-time/Useful-Tools-repos/5-website-components/WebTemplateStudio/templates/Web/Pages/Vue.List/frontend/src/components/ListItem.vue
﻿<template>
  <div class="col-12 mb-3 border">
    <div class="row">
      <div class="col-11">
        <p class="mt-3">{{listItem.text}}</p>
      </div>
      <div class="col-1">
        <button
          aria-label="delete"
          class="close py-2"
          data-dismiss="alert"
          type="button"
          alt="delete"
          @click="$emit('deleteListItem', listItem)"
        >
          <div aria-hidden="true">&times;</div>
        </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "ListItem",
  props: {
    listItem: {
      type: Object,
      required: true,
      validator: function(value) {
        return value.text !== undefined && value.id !== undefined;
      }
    }
  }
};
</script>
